TOPDIR ?= ../..
include $(TOPDIR)/.config

$(SHIFTBRITE_SUPPORT)_SRC += hardware/shiftbrite/shiftbrite.c hardware/shiftbrite/shiftbrite_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
